### ISSUE TITLE
Usability issue - Older versions of minecraft

### ISSUE THREAD

**Issue by Tome-Wyrm** [rubennp91/mcloady#7]
So, I attempted to use this on a 1.7.10 modpack (yes, I know, ancient)

And the tp command doesn't have angles as parameters in that version, nor does spectator mode exist.

Spectator is no big deal (just use creative instead, and you can do that before running the script), but passing a TP command with invalid operators just fails.

It might be nice to have some flags in the config file to enable/disable things like the angle flags?

I'm trying to edit the script myself to do this, and I'm rusty as all heck, so it's not going well :)

Edit: I'm using mcloady_singleplayer

**Comment by rubennp91** [comment]
Thanks for the suggestion, I'll add it

**Comment by rubennp91** [comment]
Fixed in https://github.com/rubennp91/mcloady/commit/d13e82900e06d85eb3832c221d5e7a8baee67014

During today I'll create a release. Thanks

**Comment by rubennp91** [comment]
I'll update the readme later but to give you a hint, I've added two new parameters in the configuration:
angles: if set to True will take into consideration angles if set to False it will not
creative: if set to True it will use creative mode instead of spectator, you will have to make sure your character is flying

Since there is no rotating, the time it is spent on a tp is the sum of first_wait + 3*second_wait. If you want to shorten it, just modify those in the configs.

Besides that, I've noticed that 0.0.0.0 doesn't work as rcon ip for 1.7.10. If you are doing it locally, change it to 'localhost'.

I've tested it in 1.7.10 and 1.20.1 (changing configs) and it worked fine.

**Comment by rubennp91** [comment]
I just pushed changes to mcloady_singleplayer. I was not able to test in 1.7.10 since my minecraft instance refuses to create a world for some reason. Please let me know if it works for you and if you need a release:

https://github.com/rubennp91/mcloady_singleplayer

**Comment by Tome-Wyrm** [comment]
It does indeed work, and I don't need a release.
Thank you :)
